
local FILE = "fonts.xml"
local SUFFIX = "OysiUI_Fonts_frizqt:"
local SIZES = {8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32}

local function N(n) return ("\n"):rep(n) end
local function T(n) return ("\t"):rep(n) end

local str = ""

str = str .. N(1)
str = str .. "<!-- Generated by https://github.com/oysi/wow-font-xml-generator -->" .. N(1)
str = str .. N(1)
str = str .. "<ui>" .. N(1)

local function run(size, outline, shadow)
	-- start
	str = str .. T(1) .. "<FontFamily name=\"" .. SUFFIX .. size .. ":" .. outline .. ":" .. shadow .. "\" virtual=\"true\">" .. N(1)
	
	local function add(alphabet, font_path, size_offset)
		str = str .. T(2) .. "<Member alphabet=\"" .. alphabet .. "\">" .. N(1)
		
		str = str .. T(3) .. "<Font font=\"" .. font_path .. "\" height=\"" .. (size + size_offset) .. "\"" .. (outline == 1 and " outline=\"NORMAL\"" or "") .. ">" .. N(1)
		
		if (shadow == 1) then
			str = str .. T(4) .. "<Shadow>" .. N(1)
			str = str .. T(5) .. "<Color r=\"0\" g=\"0\" b=\"0\" />" .. N(1)
			str = str .. T(5) .. "<Offset x=\"1\" y=\"-1\" />" .. N(1)
			str = str .. T(4) .. "</Shadow>" .. N(1)
		end
		
		str = str .. T(3) .. "</Font>" .. N(1)
		
		str = str .. T(2) .. "</Member>" .. N(1)
	end
	
	add("roman"             , "Fonts/FRIZQT__.TTF"    , -2)
	add("korean"            , "Fonts/2002.TTF"        , -2)
	add("simplifiedchinese" , "Fonts/ARKai_C.ttf"     ,  0)
	add("traditionalchinese", "Fonts/arheiuhk_bd.TTF" ,  0)
	add("russian"           , "Fonts/FRIZQT___CYR.TTF", -2)
	
	str = str .. T(1) .. "</FontFamily>" .. N(1)
end

for _, size in ipairs(SIZES) do
	for outline = 0, 1 do
		for shadow = 0, 1 do
			if (not (outline == 1 and shadow == 1)) then
				run(size, outline, shadow)
			end
		end
	end
end

str = str .. "</ui>"
str = str .. N(1)

local file = io.open(FILE, "w")
file:write(str)
file:close()
