
local FILE = "fonts.xml"
local SUFFIX = "OysiUI_Font_frizqt:"
local SIZES = {8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32}

local str = ""

str = str .. "\n"
str = str .. "<!--" .. "\n"
str = str .. "\t" .. "Generated by https://github.com/oysi/wow-font-xml-generator" .. "\n"
str = str .. "\n"
str = str .. "\t" .. "FILE: " .. FILE .. "\n"
str = str .. "\t" .. "SUFFIX: " .. SUFFIX .. "\n"
str = str .. "\t" .. "SIZES: " .. tostring(SIZES) .. "\n"
str = str .. "-->" .. "\n"
str = str .. "\n"
str = str .. "<!-- Generated by https://github.com/oysi/wow-font-xml-generator -->" .. "\n"
str = str .. "\n"
str = str .. "<ui>" .. "\n"

for _, size in ipairs(SIZES) do
	for outline = 0, 1 do
		for shadow = 0, 1 do
			-- start
			str = str .. "\t" .. "<FontFamily name=\"" .. SUFFIX .. size .. ":" .. outline .. ":" .. shadow .. "\" virtual=\"true\">" .. "\n"
			
			local function add(alphabet, font_path, size_offset)
				str = str .. "\t\t" .. "<Member alphabet=\"" .. alphabet .. "\">" .. "\n"
				str = str .. "\t\t\t" .. "<Font font=\"" .. font_path .. "\" height=\"" .. (size + size_offset) .. "\">" .. "\n"
				str = str .. "\t\t\t" .. "</Font>" .. "\n"
				str = str .. "\t\t" .. "</Member>" .. "\n"
			end
			
			add("roman"             , "Fonts/FRIZQT__.TTF"    , -2)
			add("korean"            , "Fonts/2002.TTF"        , -2)
			add("simplifiedchinese" , "Fonts/ARKai_C.ttf"     , 0)
			add("traditionalchinese", "Fonts/arheiuhk_bd.TTF" , 0)
			add("russian"           , "Fonts/FRIZQT___CYR.TTF", -2)
			
			str = str .. "\t" .. "</FontFamily>" .. "\n"
		end
	end
end

str = str .. "</ui>"
str = str .. "\n"

local file = io.open(FILE, "w")
file:write(str)
file:close()

--[[
<Member alphabet="roman">
<Font font="Fonts\FRIZQT__.TTF" height="14">
	<Shadow x="1" y="-1"> <Color r="0" g="0" b="0"/> </Shadow>
</Font>
</Member>
<Member alphabet="korean">
<Font font="Fonts\2002.TTF" height="14">
	<Shadow x="1" y="-1"> <Color r="0" g="0" b="0"/> </Shadow>
</Font>
</Member>
<Member alphabet="simplifiedchinese">
<Font font="Fonts\ARKai_C.ttf" height="16">
	<Shadow x="1" y="-1"> <Color r="0" g="0" b="0"/> </Shadow>
</Font>
</Member>
<Member alphabet="traditionalchinese">
<Font font="Fonts\arheiuhk_bd.TTF" height="16">
	<Shadow x="1" y="-1"> <Color r="0" g="0" b="0"/> </Shadow>
</Font>
</Member>
<Member alphabet="russian">
<Font font="Fonts\FRIZQT___CYR.TTF" height="14">
	<Shadow x="1" y="-1"> <Color r="0" g="0" b="0"/> </Shadow>
</Font>
</Member>
--]]
